!ifndef TJUAEUI_INSTALLER_ERRORS_NSH
!define TJUAEUI_INSTALLER_ERRORS_NSH

!include "${PROJECT_DIR}\resources\windows\installer-messages.nsh"

!define TJUAEUI_E_UNINSTALLER_COPY_OR_REBUILD_FAILED "E1001"
!define TJUAEUI_E_OLD_UNINSTALL_FAILED "E1002"
!define TJUAEUI_E_INSTALL_DIR_REMOVE_OR_LOCKED "E1003"
!define TJUAEUI_E_EXTRACT_FAILED "E1010"
!define TJUAEUI_E_DISK_INSUFFICIENT "E1020"
!define TJUAEUI_E_BUNDLED_TJUAECORE_INCOMPLETE "E1030"
!define TJUAEUI_E_CORE_APP_FILES_INCOMPLETE "E1031"
!define TJUAEUI_E_ARCH_MISMATCH "E1040"
!define TJUAEUI_E_ACTIVE_INSTALLER_CONFLICT "E1050"
!define TJUAEUI_E_REGISTRY_STATE_INVALID "E1060"
!define TJUAEUI_E_ACTIVE_MARKER_WRITE_FAILED "E1070"
!define TJUAEUI_E_INVALID_INSTALL_PATH "E1090"

!macro TJUAEUI_FAIL_UX _CODE _DETAIL _MSG_ZH _MSG_EN _ACTION_ZH _ACTION_EN _DIAGNOSTICS_ZH _DIAGNOSTICS_EN
  !insertmacro TJUAEUI_SLOG "event=session-end result=fail code=${_CODE} detail=${_DETAIL}"
  ${IfNot} ${Silent}
    MessageBox MB_OK|MB_ICONSTOP \
      "${TJUAEUI_MSG_INSTALL_FAILED_ZH} (${_CODE})$\r$\n$\r$\n\
      ${_MSG_ZH}$\r$\n$\r$\n\
      ${TJUAEUI_MSG_SUGGESTED_ACTION_ZH}:$\r$\n${_ACTION_ZH}$\r$\n$\r$\n\
      ${TJUAEUI_MSG_DIAGNOSTICS_ZH}:$\r$\n${_DIAGNOSTICS_ZH}$\r$\n$\r$\n\
      ${TJUAEUI_MSG_INSTALLER_LOG_ZH}:$\r$\n$TjuaeUISessionLogPath$\r$\n$\r$\n\
      ${TJUAEUI_MSG_BLOCK_SEPARATOR}$\r$\n$\r$\n\
      ${TJUAEUI_MSG_INSTALL_FAILED_EN} (${_CODE})$\r$\n$\r$\n\
      ${_MSG_EN}$\r$\n$\r$\n\
      ${TJUAEUI_MSG_SUGGESTED_ACTION_EN}:$\r$\n${_ACTION_EN}$\r$\n$\r$\n\
      ${TJUAEUI_MSG_DIAGNOSTICS_EN}:$\r$\n${_DIAGNOSTICS_EN}$\r$\n$\r$\n\
      ${TJUAEUI_MSG_INSTALLER_LOG_EN}:$\r$\n$TjuaeUISessionLogPath" \
      /SD IDOK
  ${EndIf}
  !insertmacro TJUAEUI_CLEAR_ACTIVE_INSTALLER_MARKER
  SetErrorLevel 2
  Quit
!macroend

!macro TJUAEUI_FAIL _CODE _DETAIL _MSG_EN _ACTION_EN
  !insertmacro TJUAEUI_FAIL_UX ${_CODE} "${_DETAIL}" "${TJUAEUI_MSG_GENERIC_FAILURE_ZH}" "${_MSG_EN}" "${TJUAEUI_MSG_GENERIC_ACTION_ZH}" "${_ACTION_EN}" "${_DETAIL}" "${_DETAIL}"
!macroend

!macro TJUAEUI_FAIL_ROOTED _ROOT_CODE _WRAPPER_CODE _DETAIL _MSG_EN _ACTION_EN
  !insertmacro TJUAEUI_FAIL_UX "${_ROOT_CODE}" "wrapperCode=${_WRAPPER_CODE} ${_DETAIL}" "${TJUAEUI_MSG_GENERIC_FAILURE_ZH}" "${_MSG_EN}" "${TJUAEUI_MSG_GENERIC_ACTION_ZH}" "${_ACTION_EN}" "${_DETAIL}" "${_DETAIL}"
!macroend

!macro TJUAEUI_FAIL_BILINGUAL _CODE _DETAIL _MSG_EN _MSG_ZH _ACTION_EN _ACTION_ZH
  !insertmacro TJUAEUI_FAIL_UX ${_CODE} "${_DETAIL}" "${_MSG_ZH}" "${_MSG_EN}" "${_ACTION_ZH}" "${_ACTION_EN}" "${_DETAIL}" "${_DETAIL}"
!macroend

!macro TJUAEUI_FAIL_ROOTED_BILINGUAL _ROOT_CODE _WRAPPER_CODE _DETAIL _MSG_EN _MSG_ZH _ACTION_EN _ACTION_ZH
  !insertmacro TJUAEUI_FAIL_UX "${_ROOT_CODE}" "wrapperCode=${_WRAPPER_CODE} ${_DETAIL}" "${_MSG_ZH}" "${_MSG_EN}" "${_ACTION_ZH}" "${_ACTION_EN}" "${_DETAIL}" "${_DETAIL}"
!macroend

!macro TJUAEUI_FAIL_BILINGUAL_DIAGNOSTICS _CODE _DETAIL _MSG_EN _MSG_ZH _ACTION_EN _ACTION_ZH _DIAGNOSTICS_EN _DIAGNOSTICS_ZH
  !insertmacro TJUAEUI_FAIL_UX ${_CODE} "${_DETAIL}" "${_MSG_ZH}" "${_MSG_EN}" "${_ACTION_ZH}" "${_ACTION_EN}" "${_DIAGNOSTICS_ZH}" "${_DIAGNOSTICS_EN}"
!macroend

!macro TJUAEUI_FAIL_ROOTED_BILINGUAL_DIAGNOSTICS _ROOT_CODE _WRAPPER_CODE _DETAIL _MSG_EN _MSG_ZH _ACTION_EN _ACTION_ZH _DIAGNOSTICS_EN _DIAGNOSTICS_ZH
  !insertmacro TJUAEUI_FAIL_UX "${_ROOT_CODE}" "wrapperCode=${_WRAPPER_CODE} ${_DETAIL}" "${_MSG_ZH}" "${_MSG_EN}" "${_ACTION_ZH}" "${_ACTION_EN}" "${_DIAGNOSTICS_ZH}" "${_DIAGNOSTICS_EN}"
!macroend

!endif
